-  hosts: namenode
   vars_files:
     - name_var.yml
   tasks:
   - name: "Copying the hadoop software file"
     copy:
       src: "{{ hadoop_path }}"
       dest: "/root"

   - name: "Copying the jdk software file"
     copy:
       src: "{{ jdk_path }}"
       dest: "/root"

   - name: "Installing jdk in the namenode"
     command: "rpm -ivh {{ jdk_software }}"
     ignore_errors: yes

   - name: "Installing hadoop in the namenode"
     command: "rpm -ivh {{ hadoop_software }} --force"
     ignore_errors: yes
   
   - name: "Copying hdfs-site.xml file"
     template:
       src: "{{ hdfs_file }}"
       dest: "/etc/hadoop"

   - name: "Copying core-site.xml file"
     copy:
       src: "{{ core_file }}"
       dest: "/etc/hadoop"

   - name: "Deleting the directory in namenode"
     shell: "{{ deleting_directory }}"
     ignore_errors: yes

   - name: "Creating directory in namenode"
     file:
       state: directory
       path: "{{ namenode_directory }}"

   - name: "Formatting namenode"
     shell: "echo Y | hadoop namenode -format"

   - name: "Stopping namenode"
     shell: "{{ stop_namenode }}"
     ignore_errors: yes

   - name: "Starting namenode"
     shell: "{{ start_namenode }}"

