-  hosts: all
   tasks:
   -    name: "Repository"
        yum_repository:
          name: "Docker"
          description: "Docker Repo"
          baseurl: "https://download.docker.com/centos/linux/7/x86_64/stable"
          gpgcheck: "no"

   -    name: "creating docker package"
        package:
          name: "docker-ce-18.09.1-3.el7.x86_64"
          state: present

   -    name: "service starting"
        service:
          name: "docker"
          state: started
          enabled: yes 

   -    name: "creating folder"
        file:
          path: "/myfile"
          state: directory

   -    name: "copying local files"
        copy:
          src: "my.html"
          dest: "/myfile"

   -    pip:
           name: docker

   -    name: "pull docker image"
        docker_image:
            name: "httpd"
            source: pull  

   -    name: "creating docker container"
        community.general.docker_container: 
          name: "myweb"
          image: "httpd"
          state: started
          exposed_ports:
            - "80"
          ports:
            - "5678:80"
          volumes:
            - /myfile:/usr/local/apache2/htdocs/  

   -    name: "Allowing firewall for new port no."
        firewalld:
          port: "5678/tcp"
          state: enabled
          permanent: yes
          immediate: yes

   -    name: "Allowing firewall for new port no."
        firewalld:
          port: "80/tcp"
          state: enabled
          permanent: yes
          immediate: yes

     


